### ISSUE TITLE
DB Seed not work

### ISSUE THREAD

**Issue by iviss** [SmarchSoftware/watchtower#8] opened 2016-04-13 17:21 UTC
command: php artisan db:seed --class Smarch\Watchtower\Seeds\WatchtowerTableSeeder not work on new Laravel 5.2

Error:

 [ReflectionException]
  Class SmarchWatchtowersrcSeedsWatchtowerTableSeeder does not exist

**Comment by landjea** [comment] 2016-04-13 17:29
Did you remember to add the service provider in your config/app.php file?

**Comment by iviss** [comment] 2016-04-13 19:02
yes I did it.

**Comment by landjea** [comment] 2016-04-13 19:24
... Weird. And you did a composer update or dump auto load ?

**Comment by iviss** [comment] 2016-04-14 10:13
composer update

**Comment by landjea** [comment] 2016-04-14 10:58
I fired up a clean new Laravel 5.2 and I didn't encounter any issue with the db seeder. It worked fine using the install instructions.

When you look in your <root>\vendor\smarch\watchtower\src\Seeds folder do you see the WatchtowerTableSeeder.php class file?

**Comment by iviss** [comment] 2016-04-14 11:05
yes it's in folder

**Comment by landjea** [comment] 2016-04-14 11:24
Then there is something wrong with either your laravel install or your
watchtower install.

Is your repo available on github? I can take a look and see what is wrong
maybe.

**Comment by iviss** [comment] 2016-04-14 11:29
I try install new one laravel 5.2 and if this issue repeat, than I write again

**Comment by iviss** [comment] 2016-04-14 13:22
[~/public_html/best]# php artisan migrate
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2015_01_20_084450_create_roles_table
Migrated: 2015_01_20_084525_create_role_user_table
Migrated: 2015_01_24_080208_create_permissions_table
Migrated: 2015_01_24_080433_create_permission_role_table
Migrated: 2015_12_04_003040_add_special_role_column
 [~/public_html/best]# php artisan db:seed --class Smarch\Watchtower\Seeds\WatchtowerTableSeeder


  [ReflectionException]
  Class SmarchWatchtowerSeedsWatchtowerTableSeeder does not exist


Same problem

**Comment by landjea** [comment] 2016-04-14 21:33
Ok, I fired up another brand new one (even named it iviss) and verified it was 5.2. Then I copy/pasted the instructions and went step by step and had no problems. I can't say what is wrong with your setup unless you make it available somewhere for me to check. It really does look like you are missing the step where you add the Watchtower ServiceProvider in config/app.

Below you can see the output from my command as I did the steps, right to where I pulled out the users that were generated by the seed.

```
H:\lamp\www   Thu 04/14/2016 16:14:32.48
λ composer create-project laravel/laravel iviss --prefer-dist
Installing laravel/laravel (v5.2.29)
  - Installing laravel/laravel (v5.2.29)
    Downloading: 100%

Created project in iviss
> php -r "copy('.env.example', '.env');"

.....lots of packages downloaded and installed.....

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
> php artisan key:generate
Application key [base64:9vdE6QlyMdsXNidzMpzdhrkCYWWh5Gcxv9Zn9U7nroo=] set successfully.

H:\lamp\www   Thu 04/14/2016 16:17:10.58
λ cd iviss

H:\lamp\www\iviss   Thu 04/14/2016 16:17:49.25
λ composer require smarch/watchtower
Using version v1.1.5.3 for smarch/watchtower
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing caffeinated/shinobi (v2.3.1)
    Loading from cache

  - Installing laravelcollective/html (v5.2.4)
    Loading from cache

  - Installing smarch/watchtower (v1.1.5.3)
    Downloading: 100%

Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader

H:\lamp\www\iviss   Thu 04/14/2016 16:18:19.93
λ php artisan vendor:publish
Copied Directory [\vendor\caffeinated\shinobi\migrations] To [\database\migrations]
Copied File [\vendor\smarch\watchtower\src\Config\watchtower.php] To [\config\watchtower.php]
Copied File [\vendor\smarch\watchtower\src\Config\watchtower-menu.php] To [\config\watchtower-menu.php]
Copied Directory [\vendor\smarch\watchtower\src\Views] To [\resources\views\vendor\watchtower]
Publishing complete for tag []!

H:\lamp\www\iviss   Thu 04/14/2016 16:19:28.06
λ php artisan migrate

H:\lamp\www\iviss   Thu 04/14/2016 16:19:43.28
λ php artisan migrate
Migration table created successfully.
Migrated: 2014_10_12_000000_create_users_table
Migrated: 2014_10_12_100000_create_password_resets_table
Migrated: 2015_01_20_084450_create_roles_table
Migrated: 2015_01_20_084525_create_role_user_table
Migrated: 2015_01_24_080208_create_permissions_table
Migrated: 2015_01_24_080433_create_permission_role_table
Migrated: 2015_12_04_003040_add_special_role_column

H:\lamp\www\iviss   Thu 04/14/2016 16:20:30.01
λ php artisan db:seed --class Smarch\Watchtower\Seeds\WatchtowerTableSeeder

H:\lamp\www\iviss   Thu 04/14/2016 17:31:52.64
λ php artisan tinker
Psy Shell v0.7.2 (PHP 7.0.0 ΓÇö cli) by Justin Hileman
>>>  \Smarch\Watchtower\Models\Role::findOrFail(1)->users
=> Illuminate\Database\Eloquent\Collection {#689
     all: [
       Smarch\Watchtower\Models\User {#691
         id: 1,
         name: "admin",
         email: "admin@change.me",
         created_at: null,
         updated_at: null,
         pivot: Illuminate\Database\Eloquent\Relations\Pivot {#690
           role_id: 1,
           user_id: 1,
         },
       },
     ],
   }
>>> exit
Exit:  Goodbye.

H:\lamp\www\iviss   Thu 04/14/2016 17:32:19.53
λ
```

Let me know when/if you can make your repo available and I will eyeball it to see what is wrong in your laravel install. Thanks.

**Comment by landjea** [comment] 2016-04-18 17:29
Without an issue I can reproduce, closing case.

**Closed by landjea** 2016-04-18 17:29 UTC

**Comment by tacbephot** [comment] 2016-05-16 08:00
remove this and it will work fine 
`namespace Smarch\Watchtower\Seeds;`

**Comment by landjea** [comment] 2016-05-16 19:49
@tacbephot Why? It works fine as is as demonstrated above.

**Comment by myirongarden** [comment] 2016-05-25 08:29
i had exact same issue
copied
WatchtowerTableSeeder.php
to
database/seeds
and commented
//namespace Smarch\Watchtower\Seeds;
//use App\DB;
composer dump-autoload
php artisan db:seed --class WatchtowerTableSeeder

db got populated :)
hope this helps some other poor sod

**Comment by tomsihap** [comment] 2016-06-01 07:57
Same issue, @myirongarden solution worked ! Thanks

**Comment by landjea** [comment] 2016-06-01 11:00
Weird. It shouldn't populate the DB at all since you commented out the App\DB class. I am thinking this might be OS related. I have tested it on a couple flavours of linux and on windows 7 and 10 and it works without a hitch on all of them. The only system i don't have access to is a Mac. Are you guys able to say what systems you are using?

**Comment by tomsihap** [comment] 2016-12-19 15:02
We're 6 months later : I experience the same issue, and the same fix works. Last time was under Laravel 5.2, OSX, this time Laravel 5.3, Windows 10

**Comment by frijj2k** [comment] 2017-01-12 16:52
Same problem here on clean Laravel 5.3 install.

**Comment by tomsihap** [comment] 2017-01-17 13:20
Maybe the thread should be reopen ?
